platform :ios, '9.0'
target 'ShopAPP' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'Alamofire', '= 4.7.3'
  # Pods for ShopAPP

  target 'ShopAPPTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
